/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-reminder`; params?: Router.UnknownInputParams; } | { pathname: `/index - Copy (2)`; params?: Router.UnknownInputParams; } | { pathname: `/index - Copy (3)`; params?: Router.UnknownInputParams; } | { pathname: `/index - Copy (4)`; params?: Router.UnknownInputParams; } | { pathname: `/index - Copy`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/pins`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-reminder`; params?: Router.UnknownOutputParams; } | { pathname: `/index - Copy (2)`; params?: Router.UnknownOutputParams; } | { pathname: `/index - Copy (3)`; params?: Router.UnknownOutputParams; } | { pathname: `/index - Copy (4)`; params?: Router.UnknownOutputParams; } | { pathname: `/index - Copy`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/pins`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-reminder${`?${string}` | `#${string}` | ''}` | `/index - Copy (2)${`?${string}` | `#${string}` | ''}` | `/index - Copy (3)${`?${string}` | `#${string}` | ''}` | `/index - Copy (4)${`?${string}` | `#${string}` | ''}` | `/index - Copy${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/pins${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-reminder`; params?: Router.UnknownInputParams; } | { pathname: `/index - Copy (2)`; params?: Router.UnknownInputParams; } | { pathname: `/index - Copy (3)`; params?: Router.UnknownInputParams; } | { pathname: `/index - Copy (4)`; params?: Router.UnknownInputParams; } | { pathname: `/index - Copy`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/pins`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
